services:
  django_server:
    build:
      context: ./photo_mapper_webserver/
      dockerfile: Dockerfile
    
    entrypoint: ./entrypoint.sh

    volumes:
     - ./photo_mapper_webserver:/usr/src/app
    
    ports:
      - 8000:8000
    
    environment:
      POSTGRES_HOST: db
    
    env_file:
      - ./.env
    
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgis/postgis:17-3.5-alpine

    env_file:
      - ./.env
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s