# Generated by Django 5.2.5 on 2025-09-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gis', '0002_rename_user_photo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='photo_gis.tag'),
        ),
    ]
