# Generated by Django 5.2.5 on 2025-09-27 15:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gis', '0004_rename_datetime_photo_timestamp_alter_photo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_case_insensitive_unique_constraint'),
        ),
    ]
